num_round: 1
num_clients: 10
lr: 0.01
momentum: 0.9
n_splits: 7
batch_size: 256
epochs: 10
num_Classes : 5
patience: 3
local_epoch : 2
num_Clients_per_round_fit : 1 
num_Clients_per_round_eval : 1 

config_fit : 
  lr : 0.01 
  momentum : 0.9
  local_epochs: 1
