---


# hyperparameters
batch_size: 256
epochs: 1  
lr: 1e-3
n_clients: 10
n_splits: 3
patience: 3
num_round : 1
num_clients: 0.9
num_Classes : 5
patience: 3
local_epoch : 2
num_Clients_per_round_fit : 1 
num_Clients_per_round_eval : 1 